name: Run Python Script
on:
  schedule:
    - cron: '0 17 * * *'
      timezone: 'Asia/Shanghai'
  push:
    branches:
      - main
    paths:
      - 'dist/GH-AC-main.py'
      - '.github/workflows/python-script.yml'
  workflow_dispatch:
jobs:
  run_script:
    if: "!contains(github.event.head_commit.message, '更新了')"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up Python 3.11
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      - name: Run Python script
        run: |
          echo "程序开始运行..."
          python dist/GH-AC-main.py
          echo "程序执行完毕。"

      - name: Generate commit for each TXT
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git remote set-url origin https://x-access-token:$GH_TOKEN@github.com/${{ github.repository }}

          current_time=$(TZ='Asia/Shanghai' date +'%Y-%m-%d %H:%M:%S')

          # 定义文件列表
          txt_files=(
            "GAll.(优选-tls).txt"
            "GAll.(优选-非tls).txt"
            "GAll.(非优选).txt"
            "替换_GAll(优选-tls).txt"
            "替换_GAll(优选-非tls).txt"
          )

          # 创建临时分支避免冲突
          git checkout -B auto-commit-branch

          # 处理每个文件
          for file in "${txt_files[@]}"; do
            if [[ -f "$file" ]]; then
              # 强制添加文件到暂存区
              git add -f "$file"
              
              # 获取实际行数（排除空行）
              line_count=$(grep -v "^$" "$file" | wc -l | awk '{print $1}')
              commit_msg="更新了 ${line_count} 节点 ($current_time)"
              
              # 创建独立提交（允许空提交）
              git commit -m "$commit_msg" --allow-empty
            fi
          done

          # 推送到主分支
          git push origin auto-commit-branch:main --force
