name: Run Python Script

on:
  schedule:
    - cron: '0 17 * * *'  # 每天定时任务（北京时间 1:00 运行）
  push:
    branches:
      - main
    paths:
      - 'python-script.yml'  # 仅当 yml 被修改时触发
  workflow_dispatch:  # 手动触发

jobs:
  run_script:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python 3.11
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

    - name: Run Python script
      run: |
        python dist/GH-AC-main.py

    - name: Fix potential encoding issues
      run: |
        # 确保所有 TXT 文件都是 UTF-8 编码
        find . -type f -name "*.txt" -exec iconv -f UTF-8 -t UTF-8 {} -o {} \;

    - name: Check for changes before committing
      env:
        GH_TOKEN: ${{ secrets.GH_TOKEN }}
      run: |
        git config --global user.name "GitHub Actions"
        git config --global user.email "actions@github.com"
        git remote set-url origin https://x-access-token:${GH_TOKEN}@github.com/${{ github.repository }}.git

        # 只添加 .txt 文件，忽略缓存文件
        git add *.txt

        # 检查是否有变更
        if git diff --cached --quiet; then
          echo "No changes detected, skipping commit."
          exit 0
        fi

        # 提交每个文件
        for file in *.txt; do
          if [ -f "$file" ]; then
            count=$(wc -l < "$file")
            current_datetime=$(TZ='Asia/Shanghai' date +'%Y-%m-%d %H:%M:%S')
            git commit -m "$file 更新了 $count 个节点 ($current_datetime)"
          fi
        done

        git push || echo "Nothing to push"
