name: Auto Node Updater
on:
  schedule:
    - cron: '0 17 * * *'  # UTC时间17点(北京时间1点)
      timezone: Asia/Shanghai
  push:
    branches: [main]
    paths:
      - 'dist/GH-AC-main.py'
      - '.github/workflows/python-script.yml'
  workflow_dispatch:

jobs:
  execute-script:
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, '更新了')"
    
    steps:
    - name: Checkout Code
      uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Verify Files
      run: |
        if [ ! -f GAll.txt ]; then
          echo "::error::缺少 GAll.txt 文件"
          exit 1
        fi
        if [ ! -f AddIP.txt ]; then
          echo "::error::缺少 AddIP.txt 文件"
          exit 1
        fi

    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.11

    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests
        sudo apt-get install -y jq

    - name: Execute Script
      run: |
        python dist/GH-AC-main.py
        echo "STATS_JSON=$(cat node_stats.json)" >> $GITHUB_ENV

    - name: Commit Results
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        # 配置Git
        git config --global user.name "GitHub Actions"
        git config --global user.email "actions@github.com"
        git remote set-url origin https://x-access-token:$GH_TOKEN@github.com/${{ github.repository }}

        # 读取统计信息
        echo "$STATS_JSON" > node_stats.json
        timestamp=$(jq -r '.timestamp' node_stats.json)

        # 处理每个文件
        jq -r '.stats | to_entries[] | "\(.key) \(.value)"' node_stats.json | while read filename line_count; do
          git add "$filename"
          git commit -m "更新${filename}（${line_count}节点 @${timestamp}）" --allow-empty
        done

        # 推送所有提交
        git push origin main
