name: Run Python Script with PyArmor

on:
  push:
    branches:
      - main  # 推送到 main 分支时触发
  schedule:
    - cron: "0 17 * * *"  # 每天北京时间 1 点触发 (UTC 17 点)
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # 1️⃣ 检出仓库代码
    - name: Checkout repository
      uses: actions/checkout@v2

    # 2️⃣ 获取北京时间
    - name: Get current date and time in Beijing
      id: get_datetime
      run: |
        current_datetime=$(TZ="Asia/Shanghai" date "+%Y-%m-%d %H:%M")
        echo "current_datetime=$current_datetime" >> $GITHUB_ENV

    # 3️⃣ 设置 Python 环境
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.11'

    # 4️⃣ 安装依赖
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    # 5️⃣ 调整目录以兼容 PyArmor 读取上级目录
    - name: Adjust working directory for PyArmor
      run: |
        mkdir ../workspace
        mv * ../workspace/
        cd ../workspace
        ls -al
        python GH-AC-main.py

    # 6️⃣ 提交并推送生成的 .txt 文件到仓库根目录
    - name: Commit generated results
      run: |
        cd ../workspace
        git config --global user.name 'github-actions'
        git config --global user.email 'github-actions@github.com'
        git add "GAll(优选-tls).txt" "GAll(优选-非tls).txt"
        git commit -m "更新 ${GITHUB_ENV[current_datetime]} - 自动更新节点"
        git push
