name: Run Python Script

on:
  schedule:
    - cron: '0 17 * * *'  # 定时任务：每天北京时间凌晨1点 (UTC 时间：17:00)
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  run_script:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python 3.11
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests

    - name: Run the obfuscated Python script
      run: |
        python dist/your_obfuscated_script.py

    - name: Create push message
      id: push_message
      run: |
        # 获取当前的北京时间
        current_datetime=$(TZ='Asia/Shanghai' date +'%Y-%m-%d %H:%M:%S')
        # 计算插入的节点数（假设你的脚本会输出插入的节点数）
        insertions=10  # 这里你可以替换为脚本生成的实际值
        echo "message=更新 ${insertions} 个节点 (${current_datetime})" >> $GITHUB_ENV

    - name: Commit and push result
      run: |
        git config --global user.name "Your Name"
        git config --global user.email "youremail@example.com"
        git add .
        git commit -m "自动更新节点"
        git push
      env:
        GH_TOKEN: ${{ secrets.GH_TOKEN }}
