name: Node Updater
on:
  schedule:
    - cron: '0 17 * * *'
      timezone: Asia/Shanghai
  push:
    branches: [main]
    paths: 
      - 'dist/GH-AC-main.py'
      - '.github/workflows/python-script.yml'
  workflow_dispatch:

jobs:
  update-nodes:
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, '更新了')"
    
    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.11

    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests  # 显式安装requests库
        sudo apt-get install -y jq  # 安装JSON处理工具

    - name: Run Script
      run: |
        python dist/GH-AC-main.py
        echo "STATS_CONTENT=$(cat node_stats.json)" >> $GITHUB_ENV

    - name: Commit Changes
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        git config --global user.name "GitHub Actions"
        git config --global user.email "actions@github.com"
        git remote set-url origin https://x-access-token:$GH_TOKEN@github.com/${{ github.repository }}
        
        # 从环境变量读取统计信息
        echo "$STATS_CONTENT" > node_stats.json
        stats=$(jq -r '.stats | to_entries[] | "\(.key)=\(.value)"' node_stats.json)
        
        # 遍历所有文件
        while IFS= read -r entry; do
          filename=$(echo $entry | cut -d'=' -f1)
          line_count=$(echo $entry | cut -d'=' -f2)
          
          # 强制提交每个文件
          git add $filename
          git commit -m "更新了${line_count}节点（$(date '+%Y-%m-%d %H:%M:%S' -d @$(( $(date +%s) + 28800 )) )）" --allow-empty
        done <<< "$stats"
        
        git push origin main
