name: Run Python Script

on:
  push:
    branches:
      - main  
  schedule:
    - cron: "0 17 * * *"  
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Get current date and time in Beijing
      id: get_datetime
      run: |
        current_datetime=$(TZ="Asia/Shanghai" date "+%Y-%m-%d %H:%M")
        echo "current_datetime=$current_datetime" >> $GITHUB_ENV

    - name: Run Python script
      run: |
        cd dist
        python GH-AC-main.py
        mv GAll*.txt ../

    - name: Commit and push the results
      uses: EndBug/add-and-commit@v9
      with:
        author_name: github-actions
        author_email: github-actions@github.com
        message: "更新 $(git diff --numstat | awk '{s+=$1} END {print s}') 个节点 (${{ env.current_datetime }})"
        add: "*.txt"
