    - name: Commit each TXT file separately
      env:
        GH_TOKEN: ${{ secrets.GH_TOKEN }}
      run: |
        git config --global user.name "GitHub Actions"
        git config --global user.email "actions@github.com"
        git remote set-url origin https://x-access-token:${GH_TOKEN}@github.com/${{ github.repository }}.git

        current_datetime=$(TZ='Asia/Shanghai' date +'%Y-%m-%d %H:%M:%S')

        # 5 个固定 TXT 文件
        files=(
          "GAll.(优选-tls).txt"
          "GAll.(优选-非tls).txt"
          "GAll.(非优选).txt"
          "替换_GAll(优选-tls).txt"
          "替换_GAll(优选-非tls).txt"
        )

        # 逐个检查文件是否变更，并独立提交
        for file in "${files[@]}"; do
          if [[ -f "$file" ]]; then
            line_count=$(wc -l < "$file" | awk '{print $1}')  # 计算当前 TXT 行数
            commit_message="$file 更新了 $line_count 个节点 ($current_datetime)"

            if ! git diff --quiet "$file"; then  # 判断文件是否发生变化
              git add "$file"
              git commit -m "$commit_message"
              git push
            else
              echo "$file 无变化，跳过提交。"
            fi
          fi
        done
