name: Auto Node Update
on:
  schedule:
    - cron: '0 17 * * *'  # UTC时间17点(北京时间1点)
  push:
    branches: [main]
    paths:
      - 'dist/GH-AC-main.py'
      - '.github/workflows/python-script.yml'
  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, '更新了')"
    
    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Verify Files
      run: |
        echo "仓库文件列表:"
        ls -l
        echo "检查必要文件:"
        if [ ! -f GAll.txt ]; then
          echo "::error::缺少 GAll.txt"
          exit 1
        fi
        if [ ! -f AddIP.txt ]; then
          echo "::error::缺少 AddIP.txt"
          exit 1
        fi

    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.11

    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests
        sudo apt-get install -y jq

    - name: Execute Script
      run: |
        python dist/GH-AC-main.py
        cat node_stats.json  # 输出 node_stats.json 文件的内容，便于调试
        echo "STATS_JSON=$(cat node_stats.json | jq -c .)" >> $GITHUB_ENV

    - name: Commit Changes and Send Notifications
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        WEBHOOK_URL: ${{ secrets.WEBHOOK_URL }}  # 请确保已在 GitHub Secrets 中配置
      run: |
        echo "STATS_JSON: $STATS_JSON"
        git config --global user.name "GitHub Actions"
        git config --global user.email "actions@github.com"
        git remote set-url origin https://x-access-token:$GH_TOKEN@github.com/${{ github.repository }}
        
        # 从 STATS_JSON 中提取 UTC 时间戳
        utc_timestamp=$(echo "$STATS_JSON" | jq -r '.timestamp')
        
        # 转换为北京时间 (UTC+8)，确保正确解析
        beijing_timestamp=$(date -u -d "$utc_timestamp 8 hours" '+%Y-%m-%d %H:%M:%S')
        echo "Beijing Timestamp: $beijing_timestamp"

        # 处理每个文件
        echo "$STATS_JSON" | jq -r '.stats | keys_unsorted[]' | while read filename; do
          line_count=$(echo "$STATS_JSON" | jq -r ".stats.\"$filename\"")
          git add "$filename" || echo "文件 $filename 未找到，跳过添加"
          commit_msg="更新了 ${line_count} 个节点 北京时间 ${beijing_timestamp}"
          git commit -m "$commit_msg" --allow-empty || echo "提交 $filename 失败，可能是无变更"
          
          # 发送通知，格式为“更新了 （行数）个节点 北京时间”
          if [ -n "$WEBHOOK_URL" ]; then
            curl -X POST -H "Content-Type: application/json" \
              -d "{\"msg\": \"更新了 ${line_count} 个节点 北京时间 ${beijing_timestamp} - ${filename}\"}" \
              "$WEBHOOK_URL"
          else
            echo "警告：未设置 WEBHOOK_URL，跳过通知推送"
          fi
        done
        
        git push origin main || echo "推送失败，请检查日志"
