name: Auto Node Update
on:
  schedule:
    - cron: '0 17 * * *'  # UTC时间17点(北京时间1点)
      timezone: Asia/Shanghai
  push:
    branches: [main]
    paths:
      - 'dist/GH-AC-main.py'
      - '.github/workflows/python-script.yml'
  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, '更新了')"
    
    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Verify Files
      run: |
        echo "仓库文件列表:"
        ls -l
        echo "检查必要文件:"
        if [ ! -f GAll.txt ]; then
          echo "::error::缺少 GAll.txt"
          exit 1
        fi
        if [ ! -f AddIP.txt ]; then
          echo "::error::缺少 AddIP.txt"
          exit 1
        fi

    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.11

    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests
        sudo apt-get install -y jq

    - name: Execute Script
      run: |
        # 运行 Python 脚本并输出 JSON 格式的统计信息
        python dist/GH-AC-main.py > node_stats.json

    - name: Commit Changes
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        git config --global user.name "GitHub Actions"
        git config --global user.email "actions@github.com"
        git remote set-url origin https://x-access-token:$GH_TOKEN@github.com/${{ github.repository }}
        
        # 读取统计信息
        timestamp=$(jq -r '.timestamp' node_stats.json)
        
        # 提交每个文件
        jq -r '.stats | keys_unsorted[]' node_stats.json | while read filename; do
          line_count=$(jq -r ".stats.\"$filename\"" node_stats.json)
          
          # 强制添加文件
          git add "$filename"
          
          # 生成提交信息
          commit_msg="更新了${line_count}个节点 - ${filename} (${timestamp})"
          
          # 允许空提交
          git commit -m "$commit_msg" --allow-empty
        done
        
        # 推送所有提交
        git push origin main
