name: Run Python Script

on:
  push:
    branches:
      - main  # 触发条件为推送到 main 分支，可以根据需要修改为其他分支
  schedule:
    - cron: "0 17 * * *"  # 每天北京时间凌晨 1 点触发（UTC 17 点）
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'  # 使用 Python 3.x 版本

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt  # 安装依赖

    - name: Run Python script
      run: |
        cd dist  # 切换到 dist 目录
        python GH-AC-main.py  # 执行加密后的脚本

    - name: Commit and push the results
      uses: EndBug/add-and-commit@v7
      with:
        author_name: github-actions
        author_email: github-actions@github.com
        message: "Automated update of generated .txt files"
        add: "GAll(优选-*.txt"  # 添加生成的文件
