name: My Workflow
on:
  schedule:
    - cron: '0 0 * * *'
  push:
    branches: [main]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16 # 或其他支持的Node版本
      - run: npm install node-fetch@2  # 或 yarn add node-fetch@2  安装依赖
      - run: node gall.mjs
      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: GAll.txt
          path: GAll.txt
