name: Run gall.mjs Script and Save Results

on:
  push:
    branches:
      - main  # 或者其他你想要监听的分支
  pull_request:
    branches:
      - main  # 触发 PR 时运行
  schedule:
    - cron: '0 16 * * *'  # 每天 UTC 16:00 触发，即中国时区 0 点

jobs:
  run_script:
    runs-on: ubuntu-latest  # 运行环境选择 Ubuntu

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3  # 获取仓库代码

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'  # 设置 Node.js 版本

      - name: Run gall.mjs script
        run: node gall.mjs  # 运行 gall.mjs 脚本

      - name: List files to verify GALL.txt exists
        run: ls -al  # 列出文件，检查 GALL.txt 是否存在

      - name: Commit and push the result (GALL.txt)
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add GALL.txt  # 将生成的 GALL.txt 文件添加到 Git
          git commit -m "Add GALL.txt result" || echo "No changes to commit"  # 如果没有变化，跳过提交
          git push origin main  # 推送到主分支
