name: Run gall.mjs and Create Gist

on:
  push:
    branches:
      - main
  schedule:
    - cron: '0 0 * * *'  # 每天午夜运行
  workflow_dispatch:      # 支持手动触发

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Run gall.mjs
        id: run_gall
        run: |
          echo "Running gall.mjs..."
          node gall.mjs  # 运行你的混淆过的 JS 文件

      - name: List files to debug
        run: |
          echo "Listing current directory files:"
          ls -al  # 列出当前目录中的所有文件，确认 GALL.txt 是否生成

      - name: Check if GALL.txt exists
        run: |
          if [ -f "GALL.txt" ]; then
            echo "GALL.txt exists."
          else
            echo "GALL.txt does not exist. Creating a new one."
            echo "This is a generated file." > GALL.txt  # 自动创建文件并写入内容
          fi

      - name: Read GALL.txt file content
        id: read_txt
        run: |
          GENERATED_FILE="GALL.txt"
          CONTENT=$(cat $GENERATED_FILE)  # 读取 GALL.txt 文件的内容
          echo "File content: $CONTENT"
          echo "::set-output name=content::$CONTENT"  # 将文件内容传递给下一个步骤

      - name: Create Gist with GALL.txt content
        run: |
          CONTENT="${{ steps.read_txt.outputs.content }}"
          curl -X POST -H "Authorization: token ${{ secrets.token }}" -d "{
            \"description\": \"Generated text from gall.mjs\",
            \"public\": true,
            \"files\": {
              \"GALL.txt\": {
                \"content\": \"$CONTENT\"
              }
            }
          }" https://api.github.com/gists

      - name: Delete GALL.txt file
        run: |
          GENERATED_FILE="GALL.txt"
          if [ -f "$GENERATED_FILE" ]; then
            rm $GENERATED_FILE
            echo "$GENERATED_FILE deleted."
          else
            echo "$GENERATED_FILE not found."
          fi
