name: Run gall.mjs and Commit Result to Repository

on:
  push:
    branches:
      - main
  schedule:
    - cron: '0 0 * * *'  # 每天午夜运行
  workflow_dispatch:      # 支持手动触发

permissions:
  contents: write  # 显式允许写入仓库内容

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install node-fetch
        run: |
          npm install node-fetch@2  # 安装 node-fetch（如果需要）

      - name: Run gall.mjs and save output to GALL.txt
        run: |
          echo "Running gall.mjs and capturing output..."
          node gall.mjs > GALL.txt  # 运行 gall.mjs 并将输出保存到 GALL.txt

      - name: List files to debug
        run: |
          echo "Listing current directory files:"
          ls -al  # 列出当前目录中的所有文件，确认 GALL.txt 是否生成

      - name: Commit GALL.txt to repository
        run: |
          echo "Committing GALL.txt to the repository..."
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          git add GALL.txt  # 添加 GALL.txt 文件
          git commit -m "Add generated GALL.txt file"  # 提交
          git push https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git HEAD:main  # 使用 GITHUB_TOKEN 推送到仓库
