name: Run gall.mjs Script and Save Results

on:
  push:
    branches:
      - main  # 或者其他你想要监听的分支
  pull_request:
    branches:
      - main  # 触发 PR 时运行
  schedule:
    - cron: '0 16 * * *'  # 每天 UTC 16:00 触发，即中国时区 0 点
    # 说明：
    # cron 的格式：分钟 小时 日 月 星期
    # '0 16 * * *' 表示每天 UTC 16:00 触发，等同于中国时区的 0 点

jobs:
  run_script:
    runs-on: ubuntu-latest  # 运行环境选择 Ubuntu

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3  # 获取仓库代码

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'  # 设置 Node.js 版本

      - name: Install dependencies
        run: npm install  # 如果有依赖项需要安装

      - name: Run gall.mjs script
        run: node gall.mjs  # 运行 gall.mjs 脚本

      - name: Commit and push the result (GALL.txt)
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add GALL.txt  # 添加生成的文件
          git commit -m "Add GALL.txt result" || echo "No changes to commit"
          git push origin main  # 推送到主分支
