name: Run gall.mjs

on:
  push:
    branches:
      - main
  schedule:
    - cron: '0 0 * * *'  # 每天午夜运行
  workflow_dispatch:      # 支持手动触发

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Run gall.mjs
        id: run_gall
        run: |
          echo "Running gall.mjs..."
          node gall.mjs
          echo "Generated text file."

      - name: Read generated txt file content
        id: read_txt
        run: |
          GENERATED_FILE="output.txt"  # 假设生成的文件名为 output.txt
          CONTENT=$(cat $GENERATED_FILE)
          echo "File content: $CONTENT"
          echo "::set-output name=content::$CONTENT"

      - name: Create Gist with txt file content
        run: |
          CONTENT="${{ steps.read_txt.outputs.content }}"
          curl -X POST -H "Authorization: token ${{ secrets.token }}" -d "{
            \"description\": \"Generated text from gall.mjs\",
            \"public\": true,
            \"files\": {
              \"output.txt\": {
                \"content\": \"$CONTENT\"
              }
            }
          }" https://api.github.com/gists

      - name: Delete generated txt file
        run: |
          GENERATED_FILE="output.txt"
          if [ -f "$GENERATED_FILE" ]; then
            rm $GENERATED_FILE
            echo "$GENERATED_FILE deleted."
          else
            echo "$GENERATED_FILE not found."
          fi
