name: Run gall.mjs and commit result

on:
  push:
    branches:
      - main  # 监听 main 分支的提交
  workflow_dispatch:  # 允许手动触发工作流

jobs:
  run-gall:
    runs-on: ubuntu-latest

    steps:
    - name: Check out code
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '22.9'

    - name: Install dependencies
      run: |
        npm install

    - name: Run gall.mjs script
      run: |
        node gall.mjs

    - name: Get insertions count from git log
      run: |
        # 提取提交日志中的插入行数（插入节点数）
        INSERTIONS=$(git log -1 --stat | grep -oP '\d+(?= insertions\(\+\))' || echo "0")
        echo "Insertions: $INSERTIONS"
        echo "INSERTIONS=$INSERTIONS" >> $GITHUB_ENV

    - name: Rename file based on insertions
      run: |
        FILE_NAME="GAll-${{ env.INSERTIONS }}.txt"
        mv GAll.txt "$FILE_NAME"
        echo "Renamed file to $FILE_NAME"

    - name: Commit and push result
      env:
        GH_TOKEN: ${{ secrets.GH_TOKEN }}
      run: |
        git config --global user.name "GitHub Actions"
        git config --global user.email "actions@github.com"
        git remote set-url origin https://x-access-token:${GH_TOKEN}@github.com/${{ github.repository }}.git
        git add $FILE_NAME
        git commit -m "Auto-generated $FILE_NAME" || echo "No changes to commit"
        git push origin HEAD:main
